# Generated by Django 2.0.9 on 2019-03-04 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=django.utils.timezone.now, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
